project:
  type: book

bibliography: references.bib

google-scholar: true

# This is hack to make the
# abstract: "Eder, Franz. 2022. *Politikwissenschaftliches Arbeiten: Eine Einführung*. Innsbruck: Institut für Politikwissenschaft, Universität Innsbruck. [https://doi.org/10.25651/4.2022.0001](https://doi.org/10.25651/4.2022.0001)."

format:
  html:
    theme:
      light: [assets/theme-light.scss, assets/tables-light.scss, zephyr]
      dark:  [assets/theme-dark.scss , assets/tables-dark.scss , slate ]
    # css: assets/citation.css
    css:
    - assets/font-awesome.css
    - assets/tables.css
    link-external-newwindow: true
    template-partials:
      - title-block.html
    filters:
    - lightbox
    lightbox:
      match: auto
      effect: zoom
  # pdf:
  #   documentclass: scrreprt
  epub:
    cover-image: images/logo.png

book:
  title: "The Researcher's Guide to N3C"
  subtitle: "A National Resource for Analyzing Real-World Health Data"
  date: last-modified
  doi: 10.5281/zenodo.7306581

  # logo: images/n3c-logo-circle-large-0.png
  # logo: images/logo.png
  # favicon: images/logo.png
  cover-image: images/n3c_logo_slim.png
  # cover-image: images/logo.png
  cover-image-alt: images/n3c-logo-circle-large-0.png
  favicon: images/n3c-logo-circle-large-0.png
  repo-url: https://github.com/national-covid-cohort-collaborative/guide-to-n3c-v1
  repo-branch: main
  repo-actions: [edit, issue, source]
  sharing: [twitter, facebook]
  downloads: [epub]
  # downloads: [pdf, epub]
  google-analytics: G-5F685V8M7X

  # abstract: "Eder, Franz. 2022. *Politikwissenschaftliches Arbeiten: Eine Einführung*. Innsbruck: Institut für Politikwissenschaft, Universität Innsbruck. [https://doi.org/10.25651/4.2022.0001](https://doi.org/10.25651/4.2022.0001)."

  page-footer:
    left: |
      <a href="https://ncats.nih.gov/n3c/">N3C</a> &copy; <a href="https://creativecommons.org/licenses/by-nd/4.0/"> CC BY-ND 4</a>
    right: |
      Part of <a href="https://covid.cd2h.org/">NIH NCATS</a>.

  editor:
    - name: William H Beasley
      affiliation: University of Oklahoma Health Sciences Center
      affiliation-url: https://ouhsc.edu/bbmc/
      email: wibeasley@hotmail.com
      orcid: 0000-0002-5613-5006
    - name: Shawn O'Neil
      affiliation: University of Colorado, Anschutz
      affiliation-url: https://oneilsh.github.io/
      email: oneilsh@gmail.com
      orcid: 0000-0001-6220-7080

  chapters:
  - index.qmd
  - part: Getting Started
    chapters:
    - chapters/intro.md
    - chapters/story.md
    - chapters/cycle.md
    - chapters/governance.md
    - chapters/onboarding.md
  - part: Investigating
    chapters:
    - chapters/access.md
    - chapters/understanding.md
    - chapters/tools.md
    - chapters/practices.md
    - chapters/publishing.md
  - part: Special Topics
    chapters:
    - chapters/support.md
    - chapters/ml.md
    # - chapters/advanced.md
    # - chapters/examples.md
  - part: Back Matter
    chapters:
    - chapters/funding.md
    - references.qmd
    # - chapters/colophon.qmd
