project:
  type: book

book:
  title: Guide to N3C
  author: N3C Education Committee
  logo: images/logo.png
  # date: "11/6/2022"

  repo-url: https://github.com/national-covid-cohort-collaborative/book-of-n3c-v1
  repo-branch: main
  repo-actions: [edit, issue]
  sharing: [twitter, facebook]

  chapters:
  - index.qmd

  - part: Getting Started
    chapters:
    - ch-intro.md
    - ch-research-story.md
    - ch-lifecycle.md
    - ch-governance.md
    - ch-onboarding.md

  - part: Investigating
    chapters:
    - ch-data-access.md
    - ch-data-understanding.md
    - ch-data-analysis.md
    - ch-practices.md
    - ch-publishing.md

  - part: Special Topics
    chapters:
    - ch-support.md
    - ch-machine-learning.md
    - ch-enclave-advanced.md
    - ch-examples.md

  - part: Back Matter
    chapters:
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  # pdf:
  #   documentclass: scrreprt
