project:
  type: book

book:
  title: Guide to N3C
  author: N3C Education Committee
  logo: images/logo.png
  # date: "11/6/2022"
  chapters:
    - index.qmd
    - ch-intro.md
    - ch-research-story.md
    - ch-lifecycle.md
    - ch-governance.md
    - ch-onboarding.md
    - ch-data-access.md
    - ch-data-understanding.md
    - ch-data-analysis.md
    - ch-practices.md
    - ch-publishing.md
    - ch-support.md
    - ch-machine-learning.md
    - ch-enclave-advanced.md
    - ch-examples.md
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  # pdf:
  #   documentclass: scrreprt
