# Welcome {.unnumbered}

Welcome to [*The Researcher's Guide to N3C: A National Resource for Analyzing Real-World Health Data*](https://national-covid-cohort-collaborative.github.io/guide-to-n3c-v1/).
Here you will find guidance, information, and pointers to resources for conducting research with the [National COVID Cohort Collaborative](https://ncats.nih.gov/n3c) (N3C).

During a time of isolation and unanswered questions in an emerging pandemic, N3C was born of an urgent need to save lives. N3C was created “to acquire and harmonize data across organizations and [provide] a secure data environment to enable transparent and reproducible collaborative research.” ^[See <https://covid.cd2h.org/about>.] Dozens of technical, clinical, and regulatory experts from government agencies, healthcare organizations, academic institutions, and the private sector worked together to build the nation’s largest and most diverse set of de-identified health records to date. Today, thousands of researchers have actively engaged with N3C resulting in hundreds of scholarly products informing public policy and patient care.

N3C emphasizes community and team science values which are embodied by the structure of the organization and reflected in the following chapters. This guide originated as a project of the Education and Training Domain Team, one of the many self-organizing [teams](#sec-onboarding-dt) within N3C. An editorial committee was formed to engage with principal investigators, clinician-scientists, informaticians, data scientists, and others to condense the collective knowledge amassed in N3C. Chapters are authored and peer reviewed by a diverse group of contributors with both broad and deep domain expertise. This has been a work of heart and soul, designed to make this ground-breaking work accessible without obscuring its complexity.

N3C is continuously evolving, and we expect this book will as well. We invite you to join us in continually expanding and improving this guide, but most importantly, we invite you to get involved in one of the many avenues for impactful research that N3C provides.

Sincerely,

_The G2N3C Editorial Committee_

## Contributors

Individual chapter lead and contributor affiliations are also provided in each chapter.

_Editorial Committee_:<br>
Shawn T. O’Neil, Will Beasley, Johanna Loomba, Sharon Patrick, Kenneth J. Wilkins, Karen M. Crowley

@sec-intro -- _Introduction_:<br>
Karen M. Crowley, Shawn T. O’Neil

@sec-story -- _A Research Story_:<br>
Will Beasley, A. Jerrod Anzalone, Sharon Patrick

@sec-lifecycle -- _Data Lifecycle - From Patients to N3C Researchers_:<br>
Stephanie Hong, Bryan Laraway

@sec-governance -- _Governance, Leadership, and Operations Structures_:<br>
Christine Suver, Johanna Loomba

@sec-onboarding -- _Onboarding, Enclave Access, N3C Team Science_:<br>
Sharon Patrick, Jonathan F. Emery, Suzanne McCahan, Mary Helen Mays

@sec-access -- _Getting & Managing Data Access_:<br>
Shawn T. O’Neil, Mariam Deacy

@sec-understanding -- _Understanding the Data_:<br>
Harold P. Lehmann, Lisa Eskanazi, Sigfried Gold, Shawn T. O’Neil, Thomas Richards, Kristin Kostka

@sec-tools -- _Introducing Enclave Analysis Tools_:<br>
Amy Olex, Andrea G. Zhou, Johanna Loomba, Evan French, Shawn T. O’Neil, Steven G. Johnson

@sec-practices -- _Best Practices for Research Lifecycle_:<br>
Harold P. Lehmann, Hytham Sidky, Jimmy Phuong, Kate Bradwell, Kenneth J. Wilkins, Andrea G. Zhou, David Sahner

@sec-publishing -- _Publishing and Sharing Your Work_:<br>
Julie A. McMurry, Jeremy R. Harper, Christine Suver, Carolyn T. Bramante, Mary K. Emmett, Amit K. Saha, Farrukh M. Koraishy, A. Jerrod Anzalone, Shawn T. O’Neil

@sec-support -- _Special Topic: Help and Support:_<br>
Shawn T. O’Neil, Saad Ljazouli, Johanna Loomba, Lisa Eskanazi




Contributing Content
------------------

The N3C and its [domain teams](https://covid.cd2h.org/domain-teams) are healthiest when assimilating contributions from reseachers of different skills (*e.g.*, clinicians & informaticians), specialties (*e.g.*, endocrinology & gerontology), programming languages (*e.g.*, Python, R, & SQL) and experiences (*e.g.*, students & PIs).

Accordingly, the [guide-to-n3c-v1](https://github.com/National-COVID-Cohort-Collaborative/guide-to-n3c-v1) repository welcomes input from you.

If you see a small mistake or unclear language, we invite you to inform us in a [new issue](https://github.com/National-COVID-Cohort-Collaborative/guide-to-n3c-v1/issues) or to edit the source and submitting a [pull request](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests).  When an editor reviews and accepts your change, the website will be updated within minutes.

If you have an idea for something more substantial such as a chapter or section, please start a [new issue](https://github.com/National-COVID-Cohort-Collaborative/guide-to-n3c-v1/issues) and the N3C Educational Committee will coordinate with you where it fits best.

Platform
------------------

<!-- The section is manually duplicated between index.qmd and README.md. -->

As the chapters are being written, talk to the chapter's Lead Author to learn if it's being written in GitHub or Google Docs.  Eventually all Google Docs chapters will be translated to Markdown.  Once a chapter has been finally converted to Markdown...

### Minor Changes

To make small changes like spelling corrections, we recommend editing the source directly in GitHub.  It handles the details without your knowledge (like starting a fork and prompting your pull request).  From the appropriate page of [the book](https://national-covid-cohort-collaborative.github.io/guide-to-n3c-v1/), click on the "Edit this page <i class="fab fa-github" aria-hidden="true"></i>" button and type your change in the [GitHub editor](https://docs.github.com/en/repositories/working-with-files/managing-files/editing-files).

### Larger Changes and Additions

Substantial edits and writing are better accommodated by a text editor on your local machine that can preview the rendered content as you type.  We suggest [Visual Studio Code](https://code.visualstudio.com/) or [RStudio](https://www.rstudio.com/products/rstudio/).

### Details

You don't have to understand the rest to contribute, but for those interested:

* The majority of this book is written in a collection of [Markdown](https://guides.github.com/features/mastering-markdown/) documents and assembled by the [Quarto](https://quarto.org/).

* After your change is pushed to GitHub, a [GitHub Action](https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions) spawns a small VM that (a) collects all the Markdown documents, (b) calls [Quarto](https://quarto.org/)/[Pandoc](https://pandoc.org/) to convert them to html, and (c) moves the rendered html files to the "gh-pages" branch.

* GitHub Pages serves the contents of the [`gh-pages` branch](https://github.com/National-COVID-Cohort-Collaborative/guide-to-n3c-v1/tree/gh-pages) to anyone with a browser.

Funding and Licensing
------------------

The N3C is supported by [NIH](https://www.nih.gov/) National Center for Advancing Translational Sciences ([NCATS](https://ncats.nih.gov/)).

This book is licensed under the [Creative Commons Attribution-NoDerivatives 4.0](https://creativecommons.org/licenses/by-nd/4.0/). {{< fa brands creative-commons size=xs title="Creative Commons">}} {{< fa brands creative-commons-by size=xs title="Attribution">}} {{< fa brands creative-commons-nd size=xs title="No Derivatives">}}
